server:
  port: 8080

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    continue-on-error: true
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:tcp://localhost:9092/mem:pccafe_db
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql:

logging:
  level:
    root: info
    jdbc:
      sqlonly: info
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off