server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /pccafe_db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/workspace/project-workspace/mvp/pccafe_db;AUTO_SERVER=TRUE
    username: sa
    password: